/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_epsit_apkupgradeclient_util_BatchUtil */

#ifndef _Included_cn_epsit_apkupgradeclient_util_BatchUtil
#define _Included_cn_epsit_apkupgradeclient_util_BatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_epsit_apkupgradeclient_util_BatchUtil
 * Method:    batch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_epsit_apkupgradeclient_util_BatchUtil_batch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
